// NVIDIA NIM 兼容模型列表
export const MODELS = [
  { id: "meta/llama-3.1-405b-instruct", name: "Llama 3.1 405B Instruct" },
  { id: "meta/llama-3.1-70b-instruct", name: "Llama 3.1 70B Instruct" },
  { id: "nvidia/llama-3.1-nemotron-70b-instruct", name: "Llama 3.1 Nemotron 70B" },
  { id: "mistralai/mistral-large-2-instruct", name: "Mistral Large 2 Instruct" },
  { id: "google/gemma-2-27b-it", name: "Gemma 2 27B IT" },
  { id: "microsoft/phi-3-mini-128k-instruct", name: "Phi-3 Mini 128K" },
  { id: "z-ai/glm4.7", name: "GLM-4.7" },
  { id: "minimaxai/minimax-m2.1", name: "MiniMax M2.1" },
  { id: "minimaxai/minimax-m2.7", name: "MiniMax M2.7" },
  { id: "deepseek-ai/deepseek-v3.2", name: "DeepSeek V3.2" },
  { id: "moonshotai/kimi-k2-thinking", name: "Kimi K2 (Thinking)" },
  { id: "moonshotai/kimi-k2.5", name: "Kimi K2.5" },
  { id: "moonshotai/kimi-k2-instruct-0905", name: "Kimi K2 Instruct 0905" },
  { id: "moonshotai/kimi-k2-instruct", name: "Kimi K2 Instruct" },
  { id: "google/gemma-4-31b-it", name: "Gemma 4 31B" },
  { id: "qwen/qwen3.5-397b-a17b", name: "Qwen 3.5 397B" },
  { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen 3 Next 80B" },
  { id: "mistralai/devstral-2-123b-instruct-2512", name: "Devstral 2 123B" },
  { id: "mistralai/mistral-large-3-675b-instruct-2512", name: "Mistral Large 3 675B" },
  { id: "stockmark/stockmark-2-100b-instruct", name: "Stockmark 2 100B" },
  { id: "bytedance/seed-oss-36b-instruct", name: "Seed OSS 36B" },
  { id: "openai/gpt-oss-20b", name: "GPT OSS 20B" },
  { id: "openai/gpt-oss-120b", name: "GPT OSS 120B" },
  { id: "nvidia/llama-3.3-nemotron-super-49b-v1.5", name: "Llama 3.3 Nemotron Super 49B" },
  { id: "sarvamai/sarvam-m", name: "Sarvam M" },
  { id: "nvidia/nemotron-nano-12b-v2-vl", name: "Nemotron Nano 12B V2 VL", multimodal: true },
];
